apiVersion: v1
kind: Service

metadata:
  name: {{ include "openshift-app.fullname" . }}

spec:

  selector:
    app: {{ include "openshift-app.name" . }}

  ports:

    - port: {{ .Values.service.port }}

      targetPort: {{ .Values.container.port }}

      protocol: TCP

  type: {{ .Values.service.type }}